-- eyeVesa: LLM Integration Tables
-- Phase 3: Pro Feature (BSL 1.1 Licensed)

-- HITL summary cache: LLM-generated summaries for approval requests
CREATE TABLE hitl_summaries (
    summary_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    approval_id UUID NOT NULL REFERENCES hitl_approvals(approval_id),
    summary_text TEXT NOT NULL,
    recommendation VARCHAR(20),
    model_used VARCHAR(100) NOT NULL DEFAULT 'gpt-4',
    tokens_used INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(approval_id)
);

CREATE INDEX idx_hitl_summaries_approval ON hitl_summaries(approval_id);

-- Audit narratives: LLM-generated human-readable audit summaries
CREATE TABLE audit_narratives (
    narrative_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    agent_id UUID NOT NULL REFERENCES agents(agent_id),
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    narrative_text TEXT NOT NULL,
    key_events JSONB DEFAULT '[]',
    anomalies_detected INT DEFAULT 0,
    trust_trend VARCHAR(20),
    model_used VARCHAR(100) NOT NULL DEFAULT 'gpt-4',
    tokens_used INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_audit_narratives_agent ON audit_narratives(agent_id);
CREATE INDEX idx_audit_narratives_period ON audit_narratives(period_start, period_end);

-- Policy translations: English → Rego rules
CREATE TABLE policy_translations (
    translation_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID REFERENCES tenants(tenant_id),
    natural_language TEXT NOT NULL,
    generated_rego TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'draft',
    validated BOOLEAN DEFAULT FALSE,
    validation_errors TEXT,
    model_used VARCHAR(100) NOT NULL DEFAULT 'gpt-4',
    tokens_used INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_policy_translations_tenant ON policy_translations(tenant_id);
CREATE INDEX idx_policy_translations_status ON policy_translations(status);

-- LLM config: per-tenant LLM settings
CREATE TABLE llm_config (
    config_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    tenant_id UUID NOT NULL UNIQUE REFERENCES tenants(tenant_id),
    provider VARCHAR(50) NOT NULL DEFAULT 'openai',
    model VARCHAR(100) NOT NULL DEFAULT 'gpt-4',
    api_key_encrypted TEXT,
    api_base_url VARCHAR(500),
    max_tokens INT DEFAULT 1000,
    temperature DECIMAL(3,2) DEFAULT 0.7,
    enabled_features TEXT[] DEFAULT '{\"hitl_summary\",\"audit_narrative\",\"policy_translation\"}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_llm_config_tenant ON llm_config(tenant_id);

COMMENT ON TABLE hitl_summaries IS 'LLM-generated summaries for HITL approval requests';
COMMENT ON TABLE audit_narratives IS 'LLM-generated human-readable audit narrative summaries';
COMMENT ON TABLE policy_translations IS 'English → Rego policy translations generated by LLM';
COMMENT ON TABLE llm_config IS 'Per-tenant LLM configuration for HITL summaries, audit narratives, policy translation';