package policy

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
)

const autogenPolicyFile = "autogen_compiled.rego"

var neverEventActions = map[string]struct{}{
	"cluster.enumerate": {},
	"cluster.modify":    {},
	"cluster.delete":    {},
	"schema.migrate":    {},
	"schema.modify":     {},
	"db.migrate":        {},
	"db.drop":           {},
	"db.alter":          {},
	"policy.override":   {},
	"policy.disable":    {},
	"secrets.read":      {},
}

type PolicyAutogenWorker struct {
	db        *pgxpool.Pool
	policyDir string
}

func NewPolicyAutogenWorker(db *pgxpool.Pool, policyDir string) *PolicyAutogenWorker {
	return &PolicyAutogenWorker{db: db, policyDir: policyDir}
}

// RefinePolicies derives deterministic, narrow allow rules from repeatedly
// trusted human and audit outcomes. It never edits baseline policy files.
func (pw *PolicyAutogenWorker) RefinePolicies(ctx context.Context) error {
	rules, err := pw.loadCandidateRules(ctx)
	if err != nil {
		return err
	}

	content := buildAutogenRego(rules)
	return pw.validateAndReplace(content)
}

type autogenRule struct {
	AgentID string
	Action  string
	Count   int
}

func (pw *PolicyAutogenWorker) loadCandidateRules(ctx context.Context) ([]autogenRule, error) {
	rows, err := pw.db.Query(ctx,
		`WITH candidates AS (
			SELECT agent_id::text AS agent_id, action, COUNT(*)::int AS approvals
			FROM hitl_approvals
			WHERE status = 'approved' AND approved_at > NOW() - INTERVAL '30 days'
			GROUP BY agent_id, action
			HAVING COUNT(*) >= 10
			UNION ALL
			SELECT agent_id::text AS agent_id, action, COUNT(*)::int AS approvals
			FROM audit_logs
			WHERE result_status = 'allowed'
			  AND trust_score_after >= 0.8
			  AND created_at > NOW() - INTERVAL '30 days'
			GROUP BY agent_id, action
			HAVING COUNT(*) >= 100
		)
		SELECT agent_id, action, SUM(approvals)::int AS approvals
		FROM candidates
		GROUP BY agent_id, action
		ORDER BY approvals DESC, agent_id, action
		LIMIT 200`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var rules []autogenRule
	for rows.Next() {
		var rule autogenRule
		if err := rows.Scan(&rule.AgentID, &rule.Action, &rule.Count); err != nil {
			return nil, err
		}
		if isNeverEvent(rule.Action) {
			continue
		}
		rules = append(rules, rule)
	}
	return rules, rows.Err()
}

func buildAutogenRego(rules []autogenRule) string {
	sort.SliceStable(rules, func(i, j int) bool {
		if rules[i].AgentID == rules[j].AgentID {
			return rules[i].Action < rules[j].Action
		}
		return rules[i].AgentID < rules[j].AgentID
	})

	var b strings.Builder
	b.WriteString("package agentid.authz\n\n")
	b.WriteString("# Generated by eyeVesa self-improving policy optimizer.\n")
	b.WriteString("# Detached from authz.rego; safe reload keeps the previous engine on validation failure.\n\n")

	for _, rule := range rules {
		b.WriteString("tool_allowed {\n")
		b.WriteString("\tinput.agent.id == ")
		b.WriteString(strconv.Quote(rule.AgentID))
		b.WriteString("\n\tinput.action.tool == ")
		b.WriteString(strconv.Quote(rule.Action))
		b.WriteString("\n}\n\n")
	}

	return b.String()
}

func (pw *PolicyAutogenWorker) validateAndReplace(content string) error {
	if err := os.MkdirAll(pw.policyDir, 0755); err != nil {
		return err
	}

	candidatePath := filepath.Join(pw.policyDir, autogenPolicyFile+".candidate.rego")
	finalPath := filepath.Join(pw.policyDir, autogenPolicyFile)
	if err := os.WriteFile(candidatePath, []byte(content), 0644); err != nil {
		return err
	}
	defer os.Remove(candidatePath)

	if _, err := NewEmbeddedOPA(pw.policyDir); err != nil {
		return fmt.Errorf("reject generated policy: %w", err)
	}

	return os.Rename(candidatePath, finalPath)
}

func isNeverEvent(action string) bool {
	action = strings.ToLower(strings.TrimSpace(action))
	if action == "" {
		return true
	}
	if _, ok := neverEventActions[action]; ok {
		return true
	}
	for blocked := range neverEventActions {
		if strings.HasPrefix(action, blocked+".") || strings.HasPrefix(action, blocked+":") {
			return true
		}
	}
	return false
}
