#!/usr/bin/env bash
set -euo pipefail

DEPLOY_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
COMPOSE_FILE="$DEPLOY_DIR/deploy/docker-compose.prod.yml"
ENV_FILE="$DEPLOY_DIR/deploy/.env.prod"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[eyeVesa]${NC} $*"; }
warn()  { echo -e "${YELLOW}[eyeVesa]${NC} $*"; }
error() { echo -e "${RED}[eyeVesa]${NC} $*" >&2; exit 1; }

check_deps() {
    for cmd in docker openssl; do
        if ! command -v "$cmd" &>/dev/null; then
            error "Missing dependency: $cmd. Install it first."
        fi
    done
    if ! docker compose version &>/dev/null; then
        error "docker compose (v2) not found. Install Docker Compose v2."
    fi
}

gen_env() {
    if [ -f "$ENV_FILE" ]; then
        info "Using existing $ENV_FILE"
        return
    fi

    info "Generating $ENV_FILE ..."
    JWT_SECRET=$(openssl rand -hex 32)
    DB_PASSWORD=$(openssl rand -hex 16)

    cat > "$ENV_FILE" <<EOF
# eyeVesa Production Environment
# Generated by deploy/scripts/deploy-vps.sh
# Edit this file before deploying

DOMAIN=gateway.eyevesa.ai
DB_PASSWORD=$DB_PASSWORD
JWT_SECRET=$JWT_SECRET
RESOURCE_NAME=enterprise-resource

# Authentication
AUTH_ENABLED=true

# Notifications (optional — leave empty to disable)
SLACK_WEBHOOK_URL=
PAGERDUTY_INTEGRATION_KEY=

# Push notifications (optional — leave empty to disable)
APNS_KEY_PATH=
APNS_KEY_ID=
APNS_TEAM_ID=
APNS_BUNDLE_ID=
FCM_SERVER_KEY=
FCM_PROJECT_ID=
EOF

    info "Generated $ENV_FILE with random secrets."
    warn "Edit $ENV_FILE to set your DOMAIN and notification keys before deploying."
}

deploy() {
    info "Building and starting eyeVesa..."
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --build
    info "Waiting for services..."
    sleep 5
    docker compose -f "$COMPOSE_FILE" ps
    info ""
    info "eyeVesa is running."
    info "Gateway: https://\$(grep DOMAIN $ENV_FILE | cut -d= -f2)"
    info "MCP:     https://\$(grep DOMAIN $ENV_FILE | cut -d= -f2)/v1/mcp"
    info ""
    info "Test: curl https://\$(grep DOMAIN $ENV_FILE | cut -d= -f2)/health"
}

status() {
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps
    echo ""
    echo "Health checks:"
    curl -s http://localhost:9443/health 2>/dev/null && echo " ← core" || echo "core: DOWN"
    curl -s http://localhost:8080/health 2>/dev/null && echo " ← control" || echo "control: DOWN"
}

register_agent() {
    local name="${1:-test-agent}"
    local owner="${2:-default}"
    info "Registering agent: $name"
    curl -s -X POST http://localhost:8080/v1/agents/register \
        -H "Content-Type: application/json" \
        -d "{\"name\":\"$name\",\"owner\":\"$owner\",\"capabilities\":[\"mcp\"],\"allowed_tools\":[\"read\",\"write\"]}" | python3 -m json.tool 2>/dev/null || echo "Registration failed — is the gateway running?"
}

logs() {
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" logs -f --tail=100
}

stop() {
    info "Stopping eyeVesa..."
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" down
    info "Stopped."
}

restart() {
    stop
    deploy
}

case "${1:-}" in
    init)
        check_deps
        gen_env
        info "Next: edit $ENV_FILE, then run: $0 deploy"
        ;;
    deploy)
        check_deps
        if [ ! -f "$ENV_FILE" ]; then
            gen_env
            warn "Review $ENV_FILE before deploying. Run: $0 deploy"
            exit 0
        fi
        deploy
        ;;
    status)
        status
        ;;
    register)
        register_agent "${2:-}" "${3:-}"
        ;;
    logs)
        logs
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "eyeVesa VPS Deploy"
        echo ""
        echo "Usage: $0 <command>"
        echo ""
        echo "Commands:"
        echo "  init      Generate .env.prod with random secrets"
        echo "  deploy    Build and start all services"
        echo "  status    Show service status and health"
        echo "  register  Register a test agent"
        echo "  logs      Follow logs"
        echo "  stop      Stop all services"
        echo "  restart   Stop and redeploy"
        echo ""
        echo "Quick start:"
        echo "  1. $0 init          # generate config"
        echo "  2. edit deploy/.env.prod  # set DOMAIN"
        echo "  3. $0 deploy        # start everything"
        ;;
esac