#!/bin/bash
# eyeVesa Deploy to Google Cloud Platform
# Usage: ./deploy-gcp.sh <command>
#
# Commands:
#   init      - Create GCP project resources (artifact registry, secrets)
#   build     - Build and push Docker images to Artifact Registry
#   plan      - Run terraform plan
#   apply     - Run terraform apply
#   destroy   - Run terraform destroy
#   migrate   - Run database migrations against Cloud SQL
#   status    - Check status of Cloud Run services
#   register  - Register a test agent via the gateway
#   logs      - Stream logs from Cloud Run services
#
# Prerequisites:
#   - gcloud CLI installed and authenticated (gcloud auth login)
#   - Terraform >= 1.5 installed
#   - Docker installed
#   - Project ID set in GCP_PROJECT or .env.gcp

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$SCRIPT_DIR/.env.gcp"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

load_env() {
    if [[ -f "$ENV_FILE" ]]; then
        set -a; source "$ENV_FILE"; set +a
        info "Loaded environment from $ENV_FILE"
    else
        warn "No $ENV_FILE found — using defaults or env vars"
    fi

    : "${GCP_PROJECT:=}"
    : "${GCP_REGION:=asia-southeast1}"
    : "${GCP_ENVIRONMENT:=production}"
    : "${GCP_DOMAIN:=gateway.eyevesa.ai}"
    : "${ARTIFACT_REGISTRY:=}"

    : "${GCP_REGION:=asia-southeast1}"
    : "${GCP_ENVIRONMENT:=production}"
    : "${GCP_DOMAIN:=gateway.eyevesa.ai}"
    : "${ARTIFACT_REGISTRY:=}"

    if [[ -z "$GCP_PROJECT" ]]; then
        error "GCP_PROJECT is required. Set it in $ENV_FILE or as env var."
    fi
}

init() {
    : "${GCP_PROJECT:=eyevesa}"
    : "${GCP_REGION:=asia-southeast1}"
    : "${GCP_ENVIRONMENT:=production}"
    : "${GCP_DOMAIN:=gateway.eyevesa.ai}"
    : "${ARTIFACT_REGISTRY:=}"

    info "Initializing GCP project: $GCP_PROJECT"

    # Enable required APIs
    gcloud services enable \
        run.googleapis.com \
        sqladmin.googleapis.com \
        artifactregistry.googleapis.com \
        cloudbuild.googleapis.com \
        secretmanager.googleapis.com \
        compute.googleapis.com \
        vpcaccess.googleapis.com \
        --project="$GCP_PROJECT"

    # Create Artifact Registry repository
    : "${ARTIFACT_REGISTRY:=}"
    if [[ -z "$ARTIFACT_REGISTRY" ]]; then
        ARTIFACT_REGISTRY="eyevesa-${GCP_ENVIRONMENT}"
    fi

    if ! gcloud artifacts repositories describe "$ARTIFACT_REGISTRY" \
         --location="$GCP_REGION" --project="$GCP_PROJECT" &>/dev/null; then
        info "Creating Artifact Registry repository: $ARTIFACT_REGISTRY"
        gcloud artifacts repositories create "$ARTIFACT_REGISTRY" \
            --repository-format=Docker \
            --location="$GCP_REGION" \
            --project="$GCP_PROJECT"
    else
        info "Artifact Registry repository $ARTIFACT_REGISTRY already exists"
    fi

    # Generate secrets if they don't exist
    DB_PASSWORD=$(openssl rand -base64 32 | tr -d '=/+' | head -c 32)
    JWT_SECRET=$(openssl rand -base64 48 | tr -d '=/+' | head -c 64)
    GATEWAY_KEY=$(cd "$PROJECT_ROOT" && openssl genpkey -algorithm ED25519 2>/dev/null | base64 || echo "GENERATE_ON_FIRST_RUN")

    info "Creating Secret Manager secrets..."
    for SECRET_NAME in eyevesa-db-password eyevesa-jwt-secret eyevesa-gateway-ed25519-key; do
        if ! gcloud secrets describe "$SECRET_NAME-${GCP_ENVIRONMENT}" --project="$GCP_PROJECT" &>/dev/null; then
            gcloud secrets create "$SECRET_NAME-${GCP_ENVIRONMENT}" --project="$GCP_PROJECT" \
                --replication-policy=automatic
            info "Created secret: $SECRET_NAME-${GCP_ENVIRONMENT}"
        else
            info "Secret already exists: $SECRET_NAME-${GCP_ENVIRONMENT}"
        fi
    done

    # Write env file
    cat > "$ENV_FILE" <<EOF
# eyeVesa GCP Deployment Configuration
# Generated by deploy-gcp.sh init
GCP_PROJECT=$GCP_PROJECT
GCP_REGION=$GCP_REGION
GCP_ENVIRONMENT=$GCP_ENVIRONMENT
GCP_DOMAIN=$GCP_DOMAIN
ARTIFACT_REGISTRY=$ARTIFACT_REGISTRY
TF_VAR_project_id=$GCP_PROJECT
TF_VAR_region=$GCP_REGION
TF_VAR_environment=$GCP_ENVIRONMENT
TF_VAR_domain=$GCP_DOMAIN
TF_VAR_db_password=$DB_PASSWORD
TF_VAR_jwt_secret=$JWT_SECRET
TF_VAR_gateway_ed25519_key=$GATEWAY_KEY
EOF

    info "Environment file written to $ENV_FILE"
    warn "Review and update secrets in Secret Manager before deploying."
}

build() {
    load_env

    if [[ -z "$ARTIFACT_REGISTRY" ]]; then
        ARTIFACT_REGISTRY="eyevesa-${GCP_ENVIRONMENT}"
    fi

    REGISTRY_URL="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${ARTIFACT_REGISTRY}"

    info "Building and pushing Docker images to $REGISTRY_URL"

    # Configure Docker auth for Artifact Registry
    gcloud auth configure-docker "${GCP_REGION}-docker.pkg.dev" --project="$GCP_PROJECT"

    # Build gateway-control (Go)
    info "Building gateway-control..."
    docker build -t "${REGISTRY_URL}/gateway-control:latest" \
        -f "$PROJECT_ROOT/gateway/control-plane/Dockerfile" \
        "$PROJECT_ROOT/gateway/control-plane"
    docker push "${REGISTRY_URL}/gateway-control:latest"

    # Build gateway-core (Rust)
    info "Building gateway-core..."
    docker build -t "${REGISTRY_URL}/gateway-core:latest" \
        -f "$PROJECT_ROOT/gateway/core/Dockerfile" \
        "$PROJECT_ROOT/gateway/core"
    docker push "${REGISTRY_URL}/gateway-core:latest"

    # Build resource-adapter (Go)
    info "Building resource-adapter..."
    docker build -t "${REGISTRY_URL}/resource-adapter:latest" \
        -f "$PROJECT_ROOT/adapter/resource-adapter-go/Dockerfile" \
        "$PROJECT_ROOT/adapter/resource-adapter-go"
    docker push "${REGISTRY_URL}/resource-adapter:latest"

    info "All images pushed successfully."
}

plan() {
    load_env
    info "Running terraform plan..."
    cd "$SCRIPT_DIR"
    terraform init -backend-config="bucket=eyevesa-tfstate-${GCP_PROJECT}" 2>/dev/null || terraform init
    terraform plan \
        -var="project_id=$GCP_PROJECT" \
        -var="region=$GCP_REGION" \
        -var="environment=$GCP_ENVIRONMENT" \
        -var="domain=$GCP_DOMAIN" \
        -var="db_password=$(grep TF_VAR_db_password "$ENV_FILE" | cut -d= -f2)" \
        -var="jwt_secret=$(grep TF_VAR_jwt_secret "$ENV_FILE" | cut -d= -f2)" \
        -var="gateway_ed25519_key=$(grep TF_VAR_gateway_ed25519_key "$ENV_FILE" | cut -d= -f2)" \
        -out=tfplan
    info "Plan saved to tfplan. Run 'apply' to deploy."
}

apply() {
    load_env
    info "Applying terraform..."
    cd "$SCRIPT_DIR"
    if [[ -f tfplan ]]; then
        terraform apply tfplan
    else
        terraform apply -auto-approve \
            -var="project_id=$GCP_PROJECT" \
            -var="region=$GCP_REGION" \
            -var="environment=$GCP_ENVIRONMENT" \
            -var="domain=$GCP_DOMAIN" \
            -var="db_password=$(grep TF_VAR_db_password "$ENV_FILE" | cut -d= -f2)" \
            -var="jwt_secret=$(grep TF_VAR_jwt_secret "$ENV_FILE" | cut -d= -f2)" \
            -var="gateway_ed25519_key=$(grep TF_VAR_gateway_ed25519_key "$ENV_FILE" | cut -d= -f2)"
    fi
    info "Infrastructure deployed!"
    echo ""
    info "Gateway Core URL:      $(terraform output -raw gateway_core_url 2>/dev/null || echo 'pending')"
    info "Gateway Control URL:   $(terraform output -raw gateway_control_url 2>/dev/null || echo 'pending')"
    info "Resource Adapter URL:  $(terraform output -raw resource_adapter_url 2>/dev/null || echo 'pending')"
    info "Cloud SQL Connection:  $(terraform output -raw cloud_sql_connection 2>/dev/null || echo 'pending')"
}

destroy() {
    load_env
    warn "This will destroy all GCP resources for eyeVesa ($GCP_ENVIRONMENT)."
    read -p "Are you sure? (yes/no): " confirm
    if [[ "$confirm" != "yes" ]]; then
        info "Aborted."
        exit 0
    fi
    cd "$SCRIPT_DIR"
    terraform destroy \
        -var="project_id=$GCP_PROJECT" \
        -var="region=$GCP_REGION" \
        -var="environment=$GCP_ENVIRONMENT" \
        -var="domain=$GCP_DOMAIN" \
        -var="db_password=$(grep TF_VAR_db_password "$ENV_FILE" | cut -d= -f2)" \
        -var="jwt_secret=$(grep TF_VAR_jwt_secret "$ENV_FILE" | cut -d= -f2)" \
        -var="gateway_ed25519_key=$(grep TF_VAR_gateway_ed25519_key "$ENV_FILE" | cut -d= -f2)"
    info "Resources destroyed."
}

migrate() {
    load_env
    info "Running database migrations against Cloud SQL..."

    INSTANCE_NAME=$(terraform output -raw cloud_sql_connection 2>/dev/null)
    if [[ -z "$INSTANCE_NAME" ]]; then
        error "Could not get Cloud SQL instance name. Run 'apply' first."
    fi

    # Connect via Cloud SQL Auth Proxy and run migrations
    MIGRATIONS_DIR="$PROJECT_ROOT/registry/migrations"

    for migration_file in $(ls "$MIGRATIONS_DIR"/*.sql | sort); do
        info "Applying: $(basename "$migration_file")"
        gcloud sql connect "$INSTANCE_NAME" \
            --user=agentid \
            --database=agentid \
            --project="$GCP_PROJECT" \
            < "$migration_file"
    done

    info "All migrations applied."
}

status() {
    load_env
    info "=== Cloud Run Services ==="
    for svc in gateway-control gateway-core resource-adapter; do
        echo ""
        info "Service: ${svc}-${GCP_ENVIRONMENT}"
        gcloud run services describe "${svc}-${GCP_ENVIRONMENT}" \
            --region="$GCP_REGION" \
            --project="$GCP_PROJECT" \
            --format="table(status.conditions[0].status,status.url,status.latestCreatedRevision)" \
            2>/dev/null || warn "Service ${svc}-${GCP_ENVIRONMENT} not found"
    done

    echo ""
    info "=== Cloud SQL ==="
    gcloud sql instances describe "eyevesa-${GCP_ENVIRONMENT}" \
        --project="$GCP_PROJECT" \
        --format="table(state,connectionName,databaseVersion)" \
        2>/dev/null || warn "Database not found"

    echo ""
    info "=== Health Checks ==="
    CORE_URL=$(gcloud run services describe "gateway-core-${GCP_ENVIRONMENT}" \
        --region="$GCP_REGION" --project="$GCP_PROJECT" \
        --format="value(status.url)" 2>/dev/null || echo "")
    CONTROL_URL=$(gcloud run services describe "gateway-control-${GCP_ENVIRONMENT}" \
        --region="$GCP_REGION" --project="$GCP_PROJECT" \
        --format="value(status.url)" 2>/dev/null || echo "")

    if [[ -n "$CORE_URL" ]]; then
        info "Gateway Core: $(curl -s "${CORE_URL}/health" 2>/dev/null || echo 'unreachable')"
    fi
    if [[ -n "$CONTROL_URL" ]]; then
        info "Gateway Control: $(curl -s "${CONTROL_URL}/health" 2>/dev/null || echo 'unreachable')"
    fi
}

register() {
    load_env

    CORE_URL=$(gcloud run services describe "gateway-core-${GCP_ENVIRONMENT}" \
        --region="$GCP_REGION" --project="$GCP_PROJECT" \
        --format="value(status.url)" 2>/dev/null)

    if [[ -z "$CORE_URL" ]]; then
        error "Could not find gateway-core URL. Is it deployed?"
    fi

    info "Registering test agent at $CORE_URL..."
    curl -s -X POST "${CORE_URL}/v1/register" \
        -H "Content-Type: application/json" \
        -d '{"name":"gcp-test-agent","owner":"org:gcp-test","capabilities":["mcp"],"allowed_tools":["read","write","search"]}' | jq .
}

logs() {
    load_env

    SVC="${1:-gateway-control}"
    info "Streaming logs for ${SVC}-${GCP_ENVIRONMENT}..."
    gcloud logging read "resource.type=cloud_run_revision AND resource.labels.service_name=${SVC}-${GCP_ENVIRONMENT}" \
        --project="$GCP_PROJECT" \
        --format="table(timestamp,severity,textPayload)" \
        --limit=50 \
        --freshness=1h
}

# ──────────────────────────────────────────────────────────────────

case "${1:-help}" in
    init)     init ;;
    build)    build ;;
    plan)     plan ;;
    apply)    apply ;;
    destroy)  destroy ;;
    migrate)  migrate ;;
    status)   status ;;
    register) register ;;
    logs)     logs "$2" ;;
    help|-h|--help)
        echo "eyeVesa GCP Deployment"
        echo ""
        echo "Usage: $0 <command> [args]"
        echo ""
        echo "Commands:"
        echo "  init       Create GCP project resources (artifact registry, secrets)"
        echo "  build      Build and push Docker images to Artifact Registry"
        echo "  plan       Run terraform plan"
        echo "  apply      Run terraform apply (deploy infrastructure)"
        echo "  destroy    Run terraform destroy (teardown)"
        echo "  migrate    Run database migrations against Cloud SQL"
        echo "  status     Check status of Cloud Run services"
        echo "  register   Register a test agent via the gateway"
        echo "  logs       Stream logs from Cloud Run services"
        echo ""
        echo "Setup:"
        echo "  1. gcloud auth login"
        echo "  2. gcloud config set project YOUR_PROJECT_ID"
        echo "  3. $0 init"
        echo "  4. Review deploy/terraform/.env.gcp"
        echo "  5. $0 build"
        echo "  6. $0 plan"
        echo "  7. $0 apply"
        echo "  8. $0 migrate"
        echo "  9. $0 register"
        ;;
    *)
        error "Unknown command: $1. Run '$0 help' for usage."
        ;;
esac