apiVersion: v1
kind: Service
metadata:
  name: {{ include "eyevesa.fullname" . }}-gateway-core
  labels:
    app.kubernetes.io/name: gateway-core
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.gatewayCore.type }}
  ports:
    - port: {{ .Values.service.gatewayCore.port }}
      targetPort: 9443
      protocol: TCP
      name: https
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gateway-core
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "eyevesa.fullname" . }}-control-plane
  labels:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.controlPlane.type }}
  ports:
    - port: {{ .Values.service.controlPlane.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/instance: {{ .Release.Name }}